### ISSUE TITLE
Example failure

### ISSUE THREAD

**Issue by jeroen** [janusza/RoughSets#1]
On my machine your package fails `CMD check` with the following:

``` r
> ###########################################################
> ## Example
> ##############################################################
> data(RoughSetData)
> decision.table <- RoughSetData$pima7.dt
> 
> control <- list(alpha.precision = 0.01, type.aggregation = c("t.tnorm", "lukasiewicz"),
+                 type.relation = c("tolerance", "eq.3"), t.implicator = "lukasiewicz")
> rules <- RI.GFRS.FRST(decision.table, control)
Error in which.min(lapply(disc.list, length)) : non-numeric argument
Calls: RI.GFRS.FRST -> which.min
Execution halted
```

The problem appears in insdie `RI.GFRS.FRST` at:

``` r
    else {
      att.val.core <- disc.list[which.min(lapply(disc.list, 
        length))]
      disc.list <- disc.list[which(lapply(disc.list, function(x) {
        att.val.core %in% x
      }) == FALSE)]
    }
```

The problem is that `lapply` returns a list, whereas `which.min` expects a logical vector. I don't understand why this problem does not appear on CRAN.

**Comment by janusza** [comment]
Dear jeroenooms,

thank you for the notice. 

The problem seems to be more complex. `which.min` can actually take a list as its argument as long as the list can be converted to a numeric vector.

``` r
which.min(as.list(rnorm(10)))
```

Anyway, this is not a good practice so I've changed it. I will ask the author of this function to debug it. Could you provide more details regarding the version of the package that you are using and your operating system?

Best regards,
Andrzej Janusz

**Comment by jeroen** [comment]
You are right, it seems this was a problem in the version of r-devel which I was using, that has been fixed already.
